name: Fetch Deriv Tick Data

on:
  schedule:
    - cron: '0 */2 * * *'  # Run every 2 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for proper data tracking
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.24.3
          pip install websocket-client==1.6.1 pandas==2.0.3 apscheduler==3.10.1 python-dotenv==1.0.0 requests==2.31.0 pytz==2023.3
      
      - name: Run fetcher
        env:
          DERIV_API_TOKEN: ${{ secrets.DERIV_API_TOKEN }}
        run: python run_fetcher.py --cycles 1
      
      - name: Commit and push data
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add data/
          git commit -m "Update tick data [skip ci]" || echo "No changes to commit"
          git push
